const TestConst = {};

TestConst.tempArray = [{"countryName":"Afghanistan" ,"country2Code":"AF" ,"country3Code":"AFG" ,"nationality":"Afghan"},
	{"countryName":"Aland Islands" ,"country2Code":"AX" ,"country3Code":"ALA" ,"nationality":"Finnish"},
	{"countryName":"Albania" ,"country2Code":"AL" ,"country3Code":"ALB" ,"nationality":"Albanian"},
	{"countryName":"Algeria" ,"country2Code":"DZ" ,"country3Code":"DZA" ,"nationality":"Algerian"},
	{"countryName":"American Samoa" ,"country2Code":"AS" ,"country3Code":"ASM" ,"nationality":"American"},
	{"countryName":"Andorra" ,"country2Code":"AD" ,"country3Code":"AND" ,"nationality":"Andorran"},
	{"countryName":"Angola" ,"country2Code":"AO" ,"country3Code":"AGO" ,"nationality":"Angolan"},
	{"countryName":"Anguilla" ,"country2Code":"AI" ,"country3Code":"AIA" ,"nationality":"British"},
	{"countryName":"Antarctica" ,"country2Code":"AQ" ,"country3Code":"ATA" ,"nationality":"Antarctica"},
	{"countryName":"Antigua and Barbuda" ,"country2Code":"AG" ,"country3Code":"ATG" ,"nationality":"Antiguan or Barbudan"},
	{"countryName":"Argentina" ,"country2Code":"AR" ,"country3Code":"ARG" ,"nationality":"Argentine"},
	{"countryName":"Armenia" ,"country2Code":"AM" ,"country3Code":"ARM" ,"nationality":"Armenian"},
	{"countryName":"Aruba" ,"country2Code":"AW" ,"country3Code":"ABW" ,"nationality":"Dutch "},
	{"countryName":"Australia" ,"country2Code":"AU" ,"country3Code":"AUS" ,"nationality":"Australian"},
	{"countryName":"Austria" ,"country2Code":"AT" ,"country3Code":"AUT" ,"nationality":"Austrian"},
	{"countryName":"Azerbaijan" ,"country2Code":"AZ" ,"country3Code":"AZE" ,"nationality":"Azerbaijani"},
	{"countryName":"Bahamas" ,"country2Code":"BS" ,"country3Code":"BHS" ,"nationality":"Bahamian"},
	{"countryName":"Bahrain" ,"country2Code":"BH" ,"country3Code":"BHR" ,"nationality":"Bahraini"},
	{"countryName":"Bangladesh" ,"country2Code":"BD" ,"country3Code":"BGD" ,"nationality":"Bangladeshi"},
	{"countryName":"Barbados" ,"country2Code":"BB" ,"country3Code":"BRB" ,"nationality":"Barbadian"},
	{"countryName":"Belarus" ,"country2Code":"BY" ,"country3Code":"BLR" ,"nationality":"Belarusian"},
	{"countryName":"Belgium" ,"country2Code":"BE" ,"country3Code":"BEL" ,"nationality":"Belgian"},
	{"countryName":"Belize" ,"country2Code":"BZ" ,"country3Code":"BLZ" ,"nationality":"Belizean"},
	{"countryName":"Benin" ,"country2Code":"BJ" ,"country3Code":"BEN" ,"nationality":"Beninese, Beninois"},
	{"countryName":"Bermuda" ,"country2Code":"BM" ,"country3Code":"BMU" ,"nationality":"British"},
	{"countryName":"Bhutan" ,"country2Code":"BT" ,"country3Code":"BTN" ,"nationality":"Bhutanese"},
	{"countryName":"Bolivia" ,"country2Code":"BO" ,"country3Code":"BOL" ,"nationality":"Bolivian"},
	{"countryName":"Bosnia and Herzegovina" ,"country2Code":"BA" ,"country3Code":"BIH" ,"nationality":"Bosnian or Herzegovinian"},
	{"countryName":"Botswana" ,"country2Code":"BW" ,"country3Code":"BWA" ,"nationality":"Botswanan"},
	{"countryName":"Bouvet Island" ,"country2Code":"BV" ,"country3Code":"BVT" ,"nationality":"Norwegian"},
	{"countryName":"Brazil" ,"country2Code":"BR" ,"country3Code":"BRA" ,"nationality":"Brazilian"},
	{"countryName":"Virgin Islands (British)" ,"country2Code":"VG" ,"country3Code":"VGB" ,"nationality":"British"},
	{"countryName":"British Indian Ocean Territory" ,"country2Code":"IO" ,"country3Code":"IOT" ,"nationality":"British"},
	{"countryName":"Brunei Darussalam" ,"country2Code":"BN" ,"country3Code":"BRN" ,"nationality":"Bruneian"},
	{"countryName":"Bulgaria" ,"country2Code":"BG" ,"country3Code":"BGR" ,"nationality":"Bulgarian"},
	{"countryName":"Burkina Faso" ,"country2Code":"BF" ,"country3Code":"BFA" ,"nationality":"Burkinabé"},
	{"countryName":"Burundi" ,"country2Code":"BI" ,"country3Code":"BDI" ,"nationality":"Burundian"},
	{"countryName":"Cambodia" ,"country2Code":"KH" ,"country3Code":"KHM" ,"nationality":"Cambodian"},
	{"countryName":"Cameroon" ,"country2Code":"CM" ,"country3Code":"CMR" ,"nationality":"Cameroonian"},
	{"countryName":"Canada" ,"country2Code":"CA" ,"country3Code":"CAN" ,"nationality":"Canadian"},
	{"countryName":"Cabo Verde" ,"country2Code":"CV" ,"country3Code":"CPV" ,"nationality":"Cabo Verdean"},
	{"countryName":"Cayman Islands" ,"country2Code":"KY" ,"country3Code":"CYM" ,"nationality":"British"},
	{"countryName":"Central African Republic" ,"country2Code":"CF" ,"country3Code":"CAF" ,"nationality":"Central African"},
	{"countryName":"Chad" ,"country2Code":"TD" ,"country3Code":"TCD" ,"nationality":"Chadian"},
	{"countryName":"Chile" ,"country2Code":"CL" ,"country3Code":"CHL" ,"nationality":"Chilean"},
	{"countryName":"China" ,"country2Code":"CN" ,"country3Code":"CHN" ,"nationality":"Chinese"},
	{"countryName":"Hong Kong" ,"country2Code":"HK" ,"country3Code":"HKG" ,"nationality":"Chinese"},
	{"countryName":"Macao" ,"country2Code":"MO" ,"country3Code":"MAC" ,"nationality":"Chinese"},
	{"countryName":"Christmas Island" ,"country2Code":"CX" ,"country3Code":"CXR" ,"nationality":"Australian"},
	{"countryName":"Cocos (Keeling) Islands" ,"country2Code":"CC" ,"country3Code":"CCK" ,"nationality":"Australian"},
	{"countryName":"Colombia" ,"country2Code":"CO" ,"country3Code":"COL" ,"nationality":"Colombian"},
	{"countryName":"Comoros" ,"country2Code":"KM" ,"country3Code":"COM" ,"nationality":"Comorian"},
	{"countryName":"Republic of the Congo" ,"country2Code":"CG" ,"country3Code":"COG" ,"nationality":"Congolese"},
	{"countryName":"Democratic Republic of the Congo" ,"country2Code":"CD" ,"country3Code":"COD" ,"nationality":"Congolese"},
	{"countryName":"Cook Islands" ,"country2Code":"CK" ,"country3Code":"COK" ,"nationality":"Zelanian"},
	{"countryName":"Costa Rica" ,"country2Code":"CR" ,"country3Code":"CRI" ,"nationality":"Costa Rican"},
	{"countryName":"Côte d'Ivoire" ,"country2Code":"CI" ,"country3Code":"CIV" ,"nationality":"Ivorian"},
	{"countryName":"Croatia" ,"country2Code":"HR" ,"country3Code":"HRV" ,"nationality":"Croatian"},
	{"countryName":"Cuba" ,"country2Code":"CU" ,"country3Code":"CUB" ,"nationality":"Cuban"},
	{"countryName":"Cyprus" ,"country2Code":"CY" ,"country3Code":"CYP" ,"nationality":"Cypriot"},
	{"countryName":"Czechia" ,"country2Code":"CZ" ,"country3Code":"CZE" ,"nationality":"Czech"},
	{"countryName":"Denmark" ,"country2Code":"DK" ,"country3Code":"DNK" ,"nationality":"Danish"},
	{"countryName":"Djibouti" ,"country2Code":"DJ" ,"country3Code":"DJI" ,"nationality":"Djiboutian"},
	{"countryName":"Dominica" ,"country2Code":"DM" ,"country3Code":"DMA" ,"nationality":"Dominican"},
	{"countryName":"Dominican Republic" ,"country2Code":"DO" ,"country3Code":"DOM" ,"nationality":"Dominican"},
	{"countryName":"Ecuador" ,"country2Code":"EC" ,"country3Code":"ECU" ,"nationality":"Ecuadorian"},
	{"countryName":"Egypt" ,"country2Code":"EG" ,"country3Code":"EGY" ,"nationality":"Egyptian"},
	{"countryName":"El Salvador" ,"country2Code":"SV" ,"country3Code":"SLV" ,"nationality":"Salvadoran"},
	{"countryName":"Equatorial Guinea" ,"country2Code":"GQ" ,"country3Code":"GNQ" ,"nationality":"Equatoguinean"},
	{"countryName":"Eritrea" ,"country2Code":"ER" ,"country3Code":"ERI" ,"nationality":"Eritrean"},
	{"countryName":"Estonia" ,"country2Code":"EE" ,"country3Code":"EST" ,"nationality":"Estonian"},
	{"countryName":"Ethiopia" ,"country2Code":"ET" ,"country3Code":"ETH" ,"nationality":"Ethiopian"},
	{"countryName":"Falkland Islands[Malvinas]" ,"country2Code":"FK" ,"country3Code":"FLK" ,"nationality":"British"},
	{"countryName":"Faroe Islands" ,"country2Code":"FO" ,"country3Code":"FRO" ,"nationality":"Danish"},
	{"countryName":"Fiji" ,"country2Code":"FJ" ,"country3Code":"FJI" ,"nationality":"Fijian"},
	{"countryName":"Finland" ,"country2Code":"FI" ,"country3Code":"FIN" ,"nationality":"Finnish"},
	{"countryName":"France" ,"country2Code":"FR" ,"country3Code":"FRA" ,"nationality":"French"},
	{"countryName":"French Guiana" ,"country2Code":"GF" ,"country3Code":"GUF" ,"nationality":"French"},
	{"countryName":"French Polynesia" ,"country2Code":"PF" ,"country3Code":"PYF" ,"nationality":"French"},
	{"countryName":"French Southern Territories" ,"country2Code":"TF" ,"country3Code":"ATF" ,"nationality":"French"},
	{"countryName":"Gabon" ,"country2Code":"GA" ,"country3Code":"GAB" ,"nationality":"Gabonese"},
	{"countryName":"Gambia" ,"country2Code":"GM" ,"country3Code":"GMB" ,"nationality":"Gambian"},
	{"countryName":"Georgia" ,"country2Code":"GE" ,"country3Code":"GEO" ,"nationality":"Georgian"},
	{"countryName":"Germany" ,"country2Code":"DE" ,"country3Code":"DEU" ,"nationality":"German"},
	{"countryName":"Ghana" ,"country2Code":"GH" ,"country3Code":"GHA" ,"nationality":"Ghanaian"},
	{"countryName":"Gibraltar" ,"country2Code":"GI" ,"country3Code":"GIB" ,"nationality":"Gibraltar"},
	{"countryName":"Greece" ,"country2Code":"GR" ,"country3Code":"GRC" ,"nationality":"Greek"},
	{"countryName":"Greenland" ,"country2Code":"GL" ,"country3Code":"GRL" ,"nationality":"Danish"},
	{"countryName":"Grenada" ,"country2Code":"GD" ,"country3Code":"GRD" ,"nationality":"Grenadian"},
	{"countryName":"Guadeloupe" ,"country2Code":"GP" ,"country3Code":"GLP" ,"nationality":"French"},
	{"countryName":"Guam" ,"country2Code":"GU" ,"country3Code":"GUM" ,"nationality":"American"},
	{"countryName":"Guatemala" ,"country2Code":"GT" ,"country3Code":"GTM" ,"nationality":"Guatemalan"},
	{"countryName":"Guernsey" ,"country2Code":"GG" ,"country3Code":"GGY" ,"nationality":"British"},
	{"countryName":"Guinea" ,"country2Code":"GN" ,"country3Code":"GIN" ,"nationality":"Guinean"},
	{"countryName":"Guinea-Bissau" ,"country2Code":"GW" ,"country3Code":"GNB" ,"nationality":"Bissau-Guinean"},
	{"countryName":"Guyana" ,"country2Code":"GY" ,"country3Code":"GUY" ,"nationality":"Guyanese"},
	{"countryName":"Haiti" ,"country2Code":"HT" ,"country3Code":"HTI" ,"nationality":"Haitian"},
	{"countryName":"Heard Island and Mcdonald Islands" ,"country2Code":"HM" ,"country3Code":"HMD" ,"nationality":"Austrian"},
	{"countryName":"Holy See" ,"country2Code":"VA" ,"country3Code":"VAT" ,"nationality":"Holy See"},
	{"countryName":"Honduras" ,"country2Code":"HN" ,"country3Code":"HND" ,"nationality":"Honduran"},
	{"countryName":"Hungary" ,"country2Code":"HU" ,"country3Code":"HUN" ,"nationality":"Hungarian"},
	{"countryName":"Iceland" ,"country2Code":"IS" ,"country3Code":"ISL" ,"nationality":"Icelandic"},
	{"countryName":"India" ,"country2Code":"IN" ,"country3Code":"IND" ,"nationality":"Indian"},
	{"countryName":"Indonesia" ,"country2Code":"ID" ,"country3Code":"IDN" ,"nationality":"Indonesian"},
	{"countryName":"Iran" ,"country2Code":"IR" ,"country3Code":"IRN" ,"nationality":"Iranian"},
	{"countryName":"Iraq" ,"country2Code":"IQ" ,"country3Code":"IRQ" ,"nationality":"Iraqi"},
	{"countryName":"Ireland" ,"country2Code":"IE" ,"country3Code":"IRL" ,"nationality":"Irish"},
	{"countryName":"Isle of Man" ,"country2Code":"IM" ,"country3Code":"IMN" ,"nationality":"British"},
	{"countryName":"Israel" ,"country2Code":"IL" ,"country3Code":"ISR" ,"nationality":"Israeli"},
	{"countryName":"Italy" ,"country2Code":"IT" ,"country3Code":"ITA" ,"nationality":"Italian"},
	{"countryName":"Jamaica" ,"country2Code":"JM" ,"country3Code":"JAM" ,"nationality":"Jamaican"},
	{"countryName":"Japan" ,"country2Code":"JP" ,"country3Code":"JPN" ,"nationality":"Japanese"},
	{"countryName":"Jersey" ,"country2Code":"JE" ,"country3Code":"JEY" ,"nationality":"British"},
	{"countryName":"Jordan" ,"country2Code":"JO" ,"country3Code":"JOR" ,"nationality":"Jordanian"},
	{"countryName":"Kazakhstan" ,"country2Code":"KZ" ,"country3Code":"KAZ" ,"nationality":"Kazakhstani"},
	{"countryName":"Kenya" ,"country2Code":"KE" ,"country3Code":"KEN" ,"nationality":"Kenyan"},
	{"countryName":"Kiribati" ,"country2Code":"KI" ,"country3Code":"KIR" ,"nationality":"I-Kiribati"},
	{"countryName":"North Korea" ,"country2Code":"KP" ,"country3Code":"PRK" ,"nationality":"North Korean"},
	{"countryName":"South Korea" ,"country2Code":"KR" ,"country3Code":"KOR" ,"nationality":"South Korean"},
	{"countryName":"Kuwait" ,"country2Code":"KW" ,"country3Code":"KWT" ,"nationality":"Kuwaiti"},
	{"countryName":"Philippines" ,"country2Code":"PH" ,"country3Code":"PHL" ,"nationality":"Filipino, Philippines"},
	{"countryName":"Kyrgyzstan" ,"country2Code":"KG" ,"country3Code":"KGZ" ,"nationality":"Kyrgyzstani"},
	{"countryName":"Lao People's Democratic Republic" ,"country2Code":"LA" ,"country3Code":"LAO" ,"nationality":"Laotian"},
	{"countryName":"Latvia" ,"country2Code":"LV" ,"country3Code":"LVA" ,"nationality":"Latvian"},
	{"countryName":"Lebanon" ,"country2Code":"LB" ,"country3Code":"LBN" ,"nationality":"Lebanese"},
	{"countryName":"Lesotho" ,"country2Code":"LS" ,"country3Code":"LSO" ,"nationality":"Basotho"},
	{"countryName":"Liberia" ,"country2Code":"LR" ,"country3Code":"LBR" ,"nationality":"Liberian"},
	{"countryName":"Libya" ,"country2Code":"LY" ,"country3Code":"LBY" ,"nationality":"Libyan"},
	{"countryName":"Liechtenstein" ,"country2Code":"LI" ,"country3Code":"LIE" ,"nationality":"Liechtensteiner"},
	{"countryName":"Lithuania" ,"country2Code":"LT" ,"country3Code":"LTU" ,"nationality":"Lithuanian"},
	{"countryName":"Luxembourg" ,"country2Code":"LU" ,"country3Code":"LUX" ,"nationality":"Luxembourgish"},
	{"countryName":"Macedonia" ,"country2Code":"MK" ,"country3Code":"MKD" ,"nationality":"Macedonian"},
	{"countryName":"Madagascar" ,"country2Code":"MG" ,"country3Code":"MDG" ,"nationality":"Malagasy"},
	{"countryName":"Malawi" ,"country2Code":"MW" ,"country3Code":"MWI" ,"nationality":"Malawian"},
	{"countryName":"Malaysia" ,"country2Code":"MY" ,"country3Code":"MYS" ,"nationality":"Malaysian"},
	{"countryName":"Maldives" ,"country2Code":"MV" ,"country3Code":"MDV" ,"nationality":"Maldivian"},
	{"countryName":"Mali" ,"country2Code":"ML" ,"country3Code":"MLI" ,"nationality":"Malian, Malinese"},
	{"countryName":"Malta" ,"country2Code":"MT" ,"country3Code":"MLT" ,"nationality":"Maltese"},
	{"countryName":"Marshall Islands" ,"country2Code":"MH" ,"country3Code":"MHL" ,"nationality":"Marshallese"},
	{"countryName":"Martinique" ,"country2Code":"MQ" ,"country3Code":"MTQ" ,"nationality":"Martinican"},
	{"countryName":"Mauritania" ,"country2Code":"MR" ,"country3Code":"MRT" ,"nationality":"Mauritanian"},
	{"countryName":"Mauritius" ,"country2Code":"MU" ,"country3Code":"MUS" ,"nationality":"Mauritian"},
	{"countryName":"Mayotte" ,"country2Code":"YT" ,"country3Code":"MYT" ,"nationality":"French"},
	{"countryName":"Mexico" ,"country2Code":"MX" ,"country3Code":"MEX" ,"nationality":"Mexican"},
	{"countryName":"Micronesia" ,"country2Code":"FM" ,"country3Code":"FSM" ,"nationality":"Micronesian"},
	{"countryName":"Moldova" ,"country2Code":"MD" ,"country3Code":"MDA" ,"nationality":"Moldovan"},
	{"countryName":"Monaco" ,"country2Code":"MC" ,"country3Code":"MCO" ,"nationality":"Monacan"},
	{"countryName":"Mongolia" ,"country2Code":"MN" ,"country3Code":"MNG" ,"nationality":"Mongolian"},
	{"countryName":"Montenegro" ,"country2Code":"ME" ,"country3Code":"MNE" ,"nationality":"Montenegrin"},
	{"countryName":"Montserrat" ,"country2Code":"MS" ,"country3Code":"MSR" ,"nationality":"British"},
	{"countryName":"Morocco" ,"country2Code":"MA" ,"country3Code":"MAR" ,"nationality":"Moroccan"},
	{"countryName":"Mozambique" ,"country2Code":"MZ" ,"country3Code":"MOZ" ,"nationality":"Mozambican"},
	{"countryName":"Myanmar" ,"country2Code":"MM" ,"country3Code":"MMR" ,"nationality":"Burmese"},
	{"countryName":"Namibia" ,"country2Code":"NA" ,"country3Code":"NAM" ,"nationality":"Namibian"},
	{"countryName":"Nauru" ,"country2Code":"NR" ,"country3Code":"NRU" ,"nationality":"Nauruan"},
	{"countryName":"Nepal" ,"country2Code":"NP" ,"country3Code":"NPL" ,"nationality":"Nepali"},
	{"countryName":"Netherlands" ,"country2Code":"NL" ,"country3Code":"NLD" ,"nationality":"Dutch"},
	{"countryName":"Netherlands Antilles" ,"country2Code":"AN" ,"country3Code":"ANT" ,"nationality":"Dutch"},
	{"countryName":"New Caledonia" ,"country2Code":"NC" ,"country3Code":"NCL" ,"nationality":"French"},
	{"countryName":"New Zealand" ,"country2Code":"NZ" ,"country3Code":"NZL" ,"nationality":"Zelanian"},
	{"countryName":"Nicaragua" ,"country2Code":"NI" ,"country3Code":"NIC" ,"nationality":"Nicaraguan"},
	{"countryName":"Niger" ,"country2Code":"NE" ,"country3Code":"NER" ,"nationality":"Nigerien"},
	{"countryName":"Nigeria" ,"country2Code":"NG" ,"country3Code":"NGA" ,"nationality":"Nigerian"},
	{"countryName":"Niue" ,"country2Code":"NU" ,"country3Code":"NIU" ,"nationality":"Zelanian"},
	{"countryName":"Norfolk Island" ,"country2Code":"NF" ,"country3Code":"NFK" ,"nationality":"Austrian"},
	{"countryName":"Northern Mariana Islands" ,"country2Code":"MP" ,"country3Code":"MNP" ,"nationality":"Northern Marianan"},
	{"countryName":"Norway" ,"country2Code":"NO" ,"country3Code":"NOR" ,"nationality":"Norwegian"},
	{"countryName":"Oman" ,"country2Code":"OM" ,"country3Code":"OMN" ,"nationality":"Omani"},
	{"countryName":"Pakistan" ,"country2Code":"PK" ,"country3Code":"PAK" ,"nationality":"Pakistani"},
	{"countryName":"Palau" ,"country2Code":"PW" ,"country3Code":"PLW" ,"nationality":"Palauan"},
	{"countryName":"Palestine" ,"country2Code":"PS" ,"country3Code":"PSE" ,"nationality":"Palestinian"},
	{"countryName":"Panama" ,"country2Code":"PA" ,"country3Code":"PAN" ,"nationality":"Panamanian"},
	{"countryName":"Papua New Guinea" ,"country2Code":"PG" ,"country3Code":"PNG" ,"nationality":"Papuan"},
	{"countryName":"Paraguay" ,"country2Code":"PY" ,"country3Code":"PRY" ,"nationality":"Paraguayan"},
	{"countryName":"Peru" ,"country2Code":"PE" ,"country3Code":"PER" ,"nationality":"Peruvian"},
	{"countryName":"Turks and Caicos Islands" ,"country2Code":"TC" ,"country3Code":"TCA" ,"nationality":"British"},
	{"countryName":"Tuvalu" ,"country2Code":"TV" ,"country3Code":"TUV" ,"nationality":"Tuvaluan"},
	{"countryName":"Uganda" ,"country2Code":"UG" ,"country3Code":"UGA" ,"nationality":"Ugandan"},
	{"countryName":"Ukraine" ,"country2Code":"UA" ,"country3Code":"UKR" ,"nationality":"Ukrainian"},
	{"countryName":"United Arab Emirates" ,"country2Code":"AE" ,"country3Code":"ARE" ,"nationality":"Emirian"},
	{"countryName":"United Kingdom of Great Britain and Northern Ireland" ,"country2Code":"GB" ,"country3Code":"GBR" ,"nationality":"UK, British"},
	{"countryName":"United States of America" ,"country2Code":"US" ,"country3Code":"USA" ,"nationality":"American"},
	{"countryName":"United States Minor Outlying Islands" ,"country2Code":"UM" ,"country3Code":"UMI" ,"nationality":"American"},
	{"countryName":"Uruguay" ,"country2Code":"UY" ,"country3Code":"URY" ,"nationality":"Uruguayan"},
	{"countryName":"Uzbekistan" ,"country2Code":"UZ" ,"country3Code":"UZB" ,"nationality":"Uzbekistani"},
	{"countryName":"Vanuatu" ,"country2Code":"VU" ,"country3Code":"VUT" ,"nationality":"Vanuatuan"},
	{"countryName":"Venezuela" ,"country2Code":"VE" ,"country3Code":"VEN" ,"nationality":"Venezuelan"},
	{"countryName":"Viet Nam" ,"country2Code":"VN" ,"country3Code":"VNM" ,"nationality":"Vietnamese"},
	{"countryName":"Virgin Islands (U.S.)" ,"country2Code":"VI" ,"country3Code":"VIR" ,"nationality":"American"},
	{"countryName":"Wallis and Futuna" ,"country2Code":"WF" ,"country3Code":"WLF" ,"nationality":"French"},
	{"countryName":"Western Sahara" ,"country2Code":"EH" ,"country3Code":"ESH" ,"nationality":"Sahrawi "},
	{"countryName":"Pitcairn" ,"country2Code":"PN" ,"country3Code":"PCN" ,"nationality":"British"},
	{"countryName":"Poland" ,"country2Code":"PL" ,"country3Code":"POL" ,"nationality":"Polish"},
	{"countryName":"Portugal" ,"country2Code":"PT" ,"country3Code":"PRT" ,"nationality":"Portuguese"},
	{"countryName":"Puerto Rico" ,"country2Code":"PR" ,"country3Code":"PRI" ,"nationality":"Puerto Rican"},
	{"countryName":"Qatar" ,"country2Code":"QA" ,"country3Code":"QAT" ,"nationality":"Qatari"},
	{"countryName":"Réunion" ,"country2Code":"RE" ,"country3Code":"REU" ,"nationality":"French"},
	{"countryName":"Romania" ,"country2Code":"RO" ,"country3Code":"ROU" ,"nationality":"Romanian"},
	{"countryName":"Russia" ,"country2Code":"RU" ,"country3Code":"RUS" ,"nationality":"Russian"},
	{"countryName":"Rwanda" ,"country2Code":"RW" ,"country3Code":"RWA" ,"nationality":"Rwandan"},
	{"countryName":"Saint Barthélemy " ,"country2Code":"BL" ,"country3Code":"BLM" ,"nationality":"French"},
	{"countryName":"Saint Helena, Ascension and Tristan da Cunha" ,"country2Code":"SH" ,"country3Code":"SHN" ,"nationality":"British"},
	{"countryName":"Saint Kitts and Nevis" ,"country2Code":"KN" ,"country3Code":"KNA" ,"nationality":"Kittitian or Nevisian"},
	{"countryName":"Saint Lucia" ,"country2Code":"LC" ,"country3Code":"LCA" ,"nationality":"Saint Lucian"},
	{"countryName":"Saint Martin (French part)" ,"country2Code":"MF" ,"country3Code":"MAF" ,"nationality":"French"},
	{"countryName":"Saint Pierre and Miquelon" ,"country2Code":"PM" ,"country3Code":"SPM" ,"nationality":"French"},
	{"countryName":"Saint Vincent and the Grenadines" ,"country2Code":"VC" ,"country3Code":"VCT" ,"nationality":"Saint Vincentian"},
	{"countryName":"Samoa" ,"country2Code":"WS" ,"country3Code":"WSM" ,"nationality":"Samoan"},
	{"countryName":"San Marino" ,"country2Code":"SM" ,"country3Code":"SMR" ,"nationality":"Sammarinese"},
	{"countryName":"Sao Tome and Principe" ,"country2Code":"ST" ,"country3Code":"STP" ,"nationality":"Sao Tomean"},
	{"countryName":"Saudi Arabia" ,"country2Code":"SA" ,"country3Code":"SAU" ,"nationality":"Saudi, Saudi Arabian"},
	{"countryName":"Senegal" ,"country2Code":"SN" ,"country3Code":"SEN" ,"nationality":"Senegalese"},
	{"countryName":"Serbia" ,"country2Code":"RS" ,"country3Code":"SRB" ,"nationality":"Serbian"},
	{"countryName":"Seychelles" ,"country2Code":"SC" ,"country3Code":"SYC" ,"nationality":"Seychellois"},
	{"countryName":"Sierra Leone" ,"country2Code":"SL" ,"country3Code":"SLE" ,"nationality":"Sierra Leonean"},
	{"countryName":"Singapore" ,"country2Code":"SG" ,"country3Code":"SGP" ,"nationality":"Singaporean"},
	{"countryName":"Slovakia" ,"country2Code":"SK" ,"country3Code":"SVK" ,"nationality":"Slovak"},
	{"countryName":"Slovenia" ,"country2Code":"SI" ,"country3Code":"SVN" ,"nationality":"Slovenian"},
	{"countryName":"Solomon Islands" ,"country2Code":"SB" ,"country3Code":"SLB" ,"nationality":"Solomon Island"},
	{"countryName":"Somalia" ,"country2Code":"SO" ,"country3Code":"SOM" ,"nationality":"Somali"},
	{"countryName":"South Africa" ,"country2Code":"ZA" ,"country3Code":"ZAF" ,"nationality":"South African"},
	{"countryName":"South Georgia and the South Sandwich Islands" ,"country2Code":"GS" ,"country3Code":"SGS" ,"nationality":"British"},
	{"countryName":"South Sudan" ,"country2Code":"SS" ,"country3Code":"SSD" ,"nationality":"South Sudanese"},
	{"countryName":"Spain" ,"country2Code":"ES" ,"country3Code":"ESP" ,"nationality":"Spanish"},
	{"countryName":"Sri Lanka" ,"country2Code":"LK" ,"country3Code":"LKA" ,"nationality":"Sri Lankan"},
	{"countryName":"Sudan" ,"country2Code":"SD" ,"country3Code":"SDN" ,"nationality":"Sudanese"},
	{"countryName":"Suriname" ,"country2Code":"SR" ,"country3Code":"SUR" ,"nationality":"Surinamese"},
	{"countryName":"Svalbard and Jan Mayen" ,"country2Code":"SJ" ,"country3Code":"SJM" ,"nationality":"Norwegian"},
	{"countryName":"Swaziland" ,"country2Code":"SZ" ,"country3Code":"SWZ" ,"nationality":"Swazi"},
	{"countryName":"Sweden" ,"country2Code":"SE" ,"country3Code":"SWE" ,"nationality":"Swedish"},
	{"countryName":"Switzerland" ,"country2Code":"CH" ,"country3Code":"CHE" ,"nationality":"Swiss"},
	{"countryName":"Syria" ,"country2Code":"SY" ,"country3Code":"SYR" ,"nationality":"Syrian"},
	{"countryName":"Taiwan" ,"country2Code":"TW" ,"country3Code":"TWN" ,"nationality":"Chinese"},
	{"countryName":"Tajikistan" ,"country2Code":"TJ" ,"country3Code":"TJK" ,"nationality":"Tajikistani"},
	{"countryName":"Tanzania" ,"country2Code":"TZ" ,"country3Code":"TZA" ,"nationality":"Tanzanian"},
	{"countryName":"Thailand" ,"country2Code":"TH" ,"country3Code":"THA" ,"nationality":"Thai"},
	{"countryName":"Timor-Leste" ,"country2Code":"TL" ,"country3Code":"TLS" ,"nationality":"Timorese"},
	{"countryName":"Togo" ,"country2Code":"TG" ,"country3Code":"TGO" ,"nationality":"Togolese"},
	{"countryName":"Tokelau" ,"country2Code":"TK" ,"country3Code":"TKL" ,"nationality":"Tokelauan"},
	{"countryName":"Tonga" ,"country2Code":"TO" ,"country3Code":"TON" ,"nationality":"Tongan"},
	{"countryName":"Trinidad and Tobago" ,"country2Code":"TT" ,"country3Code":"TTO" ,"nationality":"Trinidadian"},
	{"countryName":"Tunisia" ,"country2Code":"TN" ,"country3Code":"TUN" ,"nationality":"Tunisian"},
	{"countryName":"Turkey" ,"country2Code":"TR" ,"country3Code":"TUR" ,"nationality":"Turkish"},
	{"countryName":"Turkmenistan" ,"country2Code":"TM" ,"country3Code":"TKM" ,"nationality":"Turkmen"},
	{"countryName":"Yemen" ,"country2Code":"YE" ,"country3Code":"YEM" ,"nationality":"Yemeni"},
	{"countryName":"Zambia" ,"country2Code":"ZM" ,"country3Code":"ZMB" ,"nationality":"Zambian"},
	{"countryName":"Zimbabwe" ,"country2Code":"ZW" ,"country3Code":"ZWE" ,"nationality":"Zimbabwean"},
	{"countryName":"Curaçao" ,"country2Code":"CW" ,"country3Code":"CUW" ,"nationality":"Dutch"},
	{"countryName":"Bonaire, Sint Eustatius and Saba" ,"country2Code":"BQ" ,"country3Code":"BES" ,"nationality":"Dutch"},
	{"countryName":"Sint Maarten (Dutch part)" ,"country2Code":"SX" ,"country3Code":"SXM" ,"nationality":"Dutch"}]

export default TestConst;